// scripts/set-env.js
const fs = require("fs");
const path = require("path");

const apiKey = process.env.SPOONACULAR_API_KEY;

if (!apiKey) {
  console.error(
    "ERROR: SPOONACULAR_API_KEY environment variable is not set in Netlify!"
  );
  process.exit(1);
}

// Hədəf faylın yolu SİZİN İSTİFADƏ ETDİYİNİZ ADLA olmalıdır:
const targetPath = path.join(
  __dirname,
  "../src/environments/environment.development.ts"
);

const envConfigFileContent = `
// This file is generated by set-env.js during the Netlify build process
export const environment = {
  production: true,
  spoonacularApiKey: '${apiKey}'
};
`;

fs.writeFile(targetPath, envConfigFileContent, (err) => {
  if (err) {
    console.error(`Error writing ${targetPath}:`, err);
    process.exit(1);
  } else {
    console.log(`Successfully generated ${targetPath} for production build.`);
  }
});
