// scripts/set-env.js
const fs = require("fs");
const path = require("path");

// Environment dəyişəninin adının düzgün olduğundan əmin olun (Netlify-da təyin etdiyinizlə eyni)
const apiKey = process.env.SPOONACULAR_API_KEY;

if (!apiKey) {
  console.error("Error: SPOONACULAR_API_KEY environment variable not set!");
  process.exit(1); // API açarı yoxdursa, build-i xəta ilə dayandır
}

// Yaradılacaq faylın yolu (src/environments/environment.prod.ts)
const targetPath = path.join(
  __dirname,
  "../src/environments/environment.development.ts"
);

// Faylın məzmunu
const envConfigFileContent = `
// This file is generated by set-env.js during the Netlify build process
export const environment = {
  production: true,
  spoonacularApiKey: '${apiKey}'
};
`;

// Faylı yaz
fs.writeFile(targetPath, envConfigFileContent, (err) => {
  if (err) {
    console.error(`Error writing ${targetPath}:`, err);
    process.exit(1);
  } else {
    console.log(`Successfully generated ${targetPath} for production build.`);
  }
});
